---
title: "Asking for Help"
---

I receive lots of requests for help with methodological, statistical, and software problems. When asking for help with statistical software issues (e.g. Stata or R troubles), there are a few basic guidelines I request you follow that will greatly aid my ability to help you with problems such as debugging code, data management, graphing errors, getting a model to estimate correctly, convergence problems, or other common issues. The most important principle is that—when possible—you should provide me with the files necessary to reproduce the problem you are having. That is, instead of only sending problematic Stata or R output to me, also send the data and coding files necessary to reproduce the problem. Keep in mind that these guidelines apply both when you are asking for help over email and when asking for help in person. Specifically, if you provide all of the following I can—very often—adequately answer your question:

**(1)** First, ask ChatGPT, Claude, or another AI LLM. In your prompt, include "I am using Stata and am receiving an error" or "I am using R and receiving an error" and then paste the chunk of code you are having an error with, and also make sure to include the full text of the error message you receive. AI is very good at helping with errors in code.

If AI doesn't solve the issue, feel free to contact me provided you follow the suggestions below. 

**(2)** Include basic descriptive statistics of your model variables. If you use Stata, [desctable](/software/desctable/index.qmd) is an easy way to do this. 

**(3)** Send a small version of the dataset you are using that includes all necessary model variables, but excludes extraneous variables in the dataset. E.g. If you are using the GSS, do not send along a dataset with thousand of variables; if you are only using 10 variables for your analysis—only include those in the dataset you send.

**(4)** Send a coding file (e.g. do-file for Stata) that includes only the necessary code to reproduce the problem you are encountering. I.e. This file should load the appropriate dataset and estimate any models and post-estimation necessary *for the specific issue you are asking for help with*. If your problem is with data management, include only the code relevant to recoding/manipulating the specific variable(s) causing the problem. That is, you should not send the files for an entire project—only send what is necessary to reproduce your specific issue. 

**(5)** Send the relevant output that illustrates the problem and any errors messages you are encountering. E.g. This can be a Stata log-file or a text file. Again, only include output relevant to the problem you are experiencing. 

Note, please don't paste all your code or output in the email. The format often makes it unreadable and/or impossible to transfer to a syntax/do-file.
