---
title: "Research"
toc-title: "Years"
---

Click on a publication below to go to a page with a PDF of the article, the abstract, replication files, online appendices, links to the article on the journal's website, and/or links to media coverage or any other resources associated with that publication.

## Forthcoming / Online First

::: {.pub-list}

- Quadlin, Natasha, **Trenton D. Mize**, Long Doan, and Bianca Manago. Forthcoming. [What do “most people” believe and who do these beliefs represent? Race-gender prototypes and the generalized other.](/research/quadlin_mize_2026_asr.qmd) *American Sociological Review*.
- **Mize, Trenton D.** and Bing Han. Forthcoming. [Marginal effects: flexible methods for interpretation across linear and nonlinear models.](/research/mize_han_hdma_2025.qmd) In *Understanding Data Modeling and Data Analysis*, edited by David Weakliem. Edward Elgar Publishing.

:::

## 2026

::: {.pub-list}

- Han, Bing and **Trenton D. Mize**. 2026. [Doing gender, doing health: Disentangling the relationship between gender and health lifestyles.](/research/han_mize_2026_ssr.qmd) *Social Science Research*.
- **Mize, Trenton D.** and Mantas Grigorovicius. 2026. [Stereotypes and stereotyping.](/research/mize_2026_ores.qmd) In *Oxford Research Encyclopedia of Sociology*. Oxford University Press.

:::

## 2025

::: {.pub-list}

- Petts, Richard J., **Trenton D. Mize**, and Gayle Kaufman. 2025. [Does taking parental leave make you a more likeable worker? Evidence from a survey experiment.](/research/petts_mize_kaufman_2025_CWF.qmd) *Community, Work, & Family*.
- Petts, Richard J., Reilly Kincaid, **Trenton D. Mize**, and Gayle Kaufman. 2025. [Gone too long or back too soon? Perceptions of paid parental leave-taking and variations by gender and family structure.](/research/petts_et_al_JMF_2025.qmd) *Journal of Marriage and Family*.
- Long Doan, **Trenton D. Mize**, and Ronald Or. 2025. [Queer eye for the social psy: on the interplay between social psychology and sexualities.](/research/doan_mize_or_HSP_2025.qmd) In *Handbook of Social Psychology*. Springer.
- **Mize, Trenton D.** 2025. [Competence perceptions at the intersection of gender and race-ethnicity.](/research/mize_2025_spq.qmd) *Social Psychology Quarterly*.
- **Mize, Trenton D.** and Reilly Kincaid. 2025. [Role-accumulation and mental health across the life course.](/research/mize_kincaid_asr_2025.qmd) *American Sociological Review*.
- **Mize, Trenton D.** and Bing Han. 2025. [Inequality and total effect summary measures for nominal and ordinal variables.](/research/mize_han_socsci_2025.qmd) *Sociological Science*.

:::

## 2024

::: {.pub-list}

- **Mize, Trenton D.** 2024. [Divergence and convergence across presumed and actual stereotypes.](/research/mize_2024_socius.qmd) *Socius*.
- Manago, Bianca and **Trenton D. Mize**. 2024. [What is the effect of an inferred mental illness label on stigma? Theoretical and empirical challenges.](/research/managomize2024.qmd) *Socius*.
- Kaufman, Gayle, Richard J. Petts, **Trenton D. Mize**, and Taryn Wield. 2024. [Gender egalitarianism and attitudes toward parental leave.](/research/kaufman_et_al_2024_SCur.qmd) *Social Currents*.

:::

## 2023

::: {.pub-list}

- **Mize, Trenton D.** and Long Doan. 2023. [The mental health consequences of sexual identity discrepancies.](/research/mize_doan_2023_IT.qmd) In *Advancing Identity Theory, Measurement, and Research*. Springer.
- Petts, Richard J., Gayle Kaufman, and **Trenton D. Mize**. 2023. [Parental leave-taking and perceptions of workers as good parents.](/research/petts_kaufman_mize_2023_JMF.qmd) *Journal of Marriage and Family*.

:::

## 2022

::: {.pub-list}

- **Mize, Trenton D.** and Bianca Manago. 2022. [The past, present, and future of experimental methods in the social sciences.](/research/mize_manago_2022_SSR.qmd) *Social Science Research*.
- Manago, Bianca and **Trenton D. Mize**. 2022. [The status and stigma consequences of mental illness labels, deviant behavior, and fear.](/research/manago_mize_2022_SSR.qmd) *Social Science Research*.
- Petts, Richard J., **Trenton D. Mize**, and Gayle Kaufman. 2022. [Organizational policies, workplace culture, and perceived job commitment of mothers and fathers who take parental leave.](/research/petts_mize_kaufman_2022_SSR.qmd) *Social Science Research*.

:::

## 2021

::: {.pub-list}

- Manago, Bianca, **Trenton D. Mize**, and Long Doan. 2021. [Can you really study an army on the internet? Comparing how status tasks perform in the laboratory and online settings.](/research/manago_mize_doan_2022_SM.qmd) *Sociological Methodology*. 51(2):319-347.
- **Mize, Trenton D.**, Gayle Kaufman, and Richard J. Petts. 2021. [Visualizing shifts in gendered parenting attitudes during COVID-19.](/research/mize_kaufman_petts_2021_Socius.qmd) *Socius*. 7:1-3.

:::

## 2020

::: {.pub-list}

- Doan, Long and **Trenton D. Mize**. 2020. [Sexual identity disclosure among lesbian, gay, and bisexual individuals.](/research/doan_mize_2020_SocSci.qmd) *Sociological Science*. 7:504-527.

:::

## 2019

::: {.pub-list}

- **Mize, Trenton D.**, Long Doan, and J. Scott Long. 2019. [A General Framework for Comparing Predictions and Marginal Effects across Models.](/research/mize_doan_long_2019_SM.qmd) *Sociological Methodology*. 49(1):152-189.
- **Mize, Trenton D.** 2019. [Best Practices for Estimating, Interpreting, and Presenting Nonlinear Interaction Effects.](/research/mize_2019_SocSci.qmd) *Sociological Science*. 6:81-117.
- **Mize, Trenton D.** 2019. [Doing Gender by Criticizing Leaders: Public and Private Displays of Status.](/research/mize_2019_SocPro.qmd) *Social Problems*. 66(1):86-107.

:::

## 2018

::: {.pub-list}

- **Mize, Trenton D.** and Bianca Manago. 2018. [Precarious Sexuality: How Men and Women are Differentially Categorized for Similar Sexual Behavior.](/research/mize_manago_2018_ASR.qmd) *American Sociological Review*. 83(2):305-330.
- **Mize, Trenton D.** and Bianca Manago. 2018. [The Stereotype Content of Sexual Orientation.](/research/mize_manago_2018_SCur.qmd) *Social Currents*. 5(5):458-478.

:::

## 2017

::: {.pub-list}

- Benard, Stephen, Mark T. Berg, and **Trenton D. Mize**. 2017. [Does Aggression Deter or Invite Reciprocal Behavior? Considering Coercive Capacity.](/research/benard_berg_mize_2017_SPQ.qmd) *Social Psychology Quarterly*. 80(4):310-329.
- **Mize, Trenton D.** 2017. [Profiles in Health: Multiple Roles and Health Lifestyles in Early Adulthood.](/research/mize_2017_SSM.qmd) *Social Science & Medicine*. 178:196-205.

:::

## 2016

::: {.pub-list}

- **Mize, Trenton D.** 2016. [Sexual Orientation in the Labor Market.](/research/mize_2016_ASR.qmd) *American Sociological Review*. 81(6):1132-1160.
- Benard, Stephen and **Trenton D. Mize**. 2016. [Small Groups: Reflections of, and Building Blocks for Social Structure.](/research/benard_mize_2016_HCST.qmd) Pp 293-320 in *Handbook of Contemporary Sociological Theory* ed. Seth Abrutyn. Springer.

:::

## 2015

::: {.pub-list}

- **Mize, Trenton D.** 2015. [What Social Psychology Can Contribute to the Study of Sex, Gender, and Sexual Orientation.](/research/mize_2015_SocComp.qmd) *Sociology Compass*. 9(12):1066-1081.

:::

## 2011

::: {.pub-list}

- **Mize, Trenton D.** and Tré Myers. 2011. [Exploring Racial Differences on the Measurement & Experience of Emotion.](/research/mize_myers_2011_JURO.qmd) *Journal for Undergraduate Research Opportunities*. 1-16.

:::
