---
title: "Links"
---

## Personal Sites

- [My Google Scholar page](https://scholar.google.com/citations?user=tE2zP3AAAAAJ&hl=en&oi=sra)
- [My ResearchGate page](https://www.researchgate.net/profile/Trenton-Mize)
- [My BlueSky profile \@TrentonMize](https://bsky.app/profile/trentonmize.bsky.social)
- [My GitHub page](https://github.com/tdmize/data)
- [My data repository (mostly for class and workshop examples)](https://tdmize.github.io/data/)

## Current Affiliations

### Purdue University 

- [Department of Sociology](https://www.cla.purdue.edu/sociology/)
- [Department of Statistics](https://www.stat.purdue.edu/)
- [The Methodology Center at Purdue](https://www.purdue.edu/amap/)
- [Kernan Experimental Social Science Lab](https://cla.purdue.edu/academic/sociology/research/labs/joe-and-maggie-kernan-experimental-social-science-lab/)
- [Center for Families](https://centers.purdue.edu/cff/)

### Teaching

- [Statistical Horizons](https://statisticalhorizons.com/)
- [Code Horizons](https://codehorizons.com/Instructors/trenton-mize/)

### Intellectual Communities

- [Affect Control Theory](http://affectcontroltheory.org/)
- [Identity Theory](https://www.identitytheory.org/)
  - [2025 Identity Theory Conference at Purdue](/resources/it.qmd)
- [Status Characteristics and Expectation States Theory](https://sites.google.com/view/statusandexpectations/home)

## Past Affiliations

### Indiana University

- [Department of Sociology](http://www.indiana.edu/~soc/)
- [Department of Statistics](http://www.stat.indiana.edu/)
- [IU SocLab](https://www.iusoclab.com/)

### Inter-University Consortium for Political and Social Research (ICPSR)

- [ICPSR Summer Program](http://www.icpsr.umich.edu/icpsrweb/content/sumprog/about.html)

### University of Georgia

- [Department of Sociology](http://sociology.uga.edu/)
- [Laboratory for the Study of Social Interaction](https://lassi.franklinresearch.uga.edu/)
