---
title: "Software"
---

# Statistical Software

A list of Stata commands and R packages I have written. Click on the package name below to read more about each (including links to download):

## Stata

- [**balanceplot**: plots of standardized imbalance statistics](/software/balanceplot/index.qmd)
- [**cleanplots**: Stata graphics scheme for professional and accessible graphs](/software/cleanplots/index.qmd) 
- [**desctable**: professionally formatted descriptive statistics tables](/software/desctable/index.qmd)
- [**irt_coef**: *y\**-standardized coefficient estimates for item response theory models](/software/irt_coef/index.qmd)
- [**irt_me**: marginal effect estimates for item response theory models](/software/irt_me/index.qmd)
- [**lca_entropy**: entropy fit statistic calculation for latent class analysis models](/software/lca_entropy/index.qmd)
- [**mecompare**: comparing marginal effects across models](/software/mecompare/index.qmd)
- [**meinequality**: marginal effects inequality statistics](/software/meinequality/index.qmd)
- [**metest**: custom tests of marginal effects and other estimates](/software/metest/index.qmd)
- [**sgmediation2**: Stata command for Sobel-Goodman tests of statistical mediation in linear regression ](/software/sgmediation2/index.qmd)
- [**suest2**: seemingly-unrelated estimation for most regression models in Stata](/software/suest2/index.qmd)
- [**totalme**: total marginal effects estimates](/software/totalme/index.qmd)
- [**usetdm**: command to download datasets off web for class and workshop examples](/software/usetdm/index.qmd)

## R

- [**cleanplots**: cleanplots color scales and theme for `ggplot2`](/software/cleanplots_r/index.qmd)
- [**suest**: seemingly unrelated estimation for comparing predictions and marginal effects across models](/software/suest_r/index.qmd)

# Misc. Example Stata Do-Files

Below are a host of miscellaneous example Stata do-files I have collected over the years. These are examples I have created for things I do repeatedly in my own work, and/or examples I have created for common questions I receive from people looking for help.

*Note:* For most topics, you will find more extensive and more polished examples [associated with a class I teach](/teaching.qmd).

*Disclaimer:* These templates worked for me for the specific situation I faced. Consider these as starting points for your work --not guaranteed paths to success.

- [Various ways to fit a fixed effects linear model: demeaning, hybrid, between/within, correlated random effects](https://drive.google.com/file/d/1pH-FN70KJ-UCugjBR-acal15PuvztnqT/view?usp=sharing)
- [Using marginal effects and mimrgns with imputed data: main effects, interaction effects, mediation, and other cross-model comparisons](https://drive.google.com/file/d/1xJtsRfsdNJBxfmBY1buQRY67dzk4zlb_/view?usp=sharing)
- [Impute missing data with multiple hot deck, including a stratification variable that needs to be imputed](https://drive.google.com/file/d/1T-puOlF4RTCgC2DO_OVPkZF7CGnk7B-d/view?usp=sharing)
- [Examine interaction effects among predictors of latent class membership](https://drive.google.com/file/d/1v7_cGVR16HeyJpwehomwJc8jE02G68rL/view?usp=sharing)
- [Data cleaning template (empty, starting file)](https://drive.google.com/file/d/1AYR3V26eJAsFOgmj9A7HnY-XCNVLapZU/view?usp=sharing)
- [Data analysis template (empty, starting file)](https://drive.google.com/file/d/1fxEXx73N1j59KHQ35k43utS8lIItj9Wo/view?usp=sharing)
