---
title: "Teaching"
---

*Lecture slides, example Stata and R code, and other resources available via the links below*

# Workshops (3 - 4 hours)

- [Categorical Data Analysis: New Methods for Marginal Effects, Moderation, and Mediation](/teaching/cdaws.qmd)
-  [Data Visualization & Model Presentation](/teaching/dmv.qmd)
- [Data Management and Other Fundamentals for Efficient and Reproducible Research](/teaching/workflow.qmd)
- [Interaction Effects: Advanced Topics](/teaching/int.qmd)
- [Missing Data](/teaching/miss.qmd)       
- [Stata Programming—Tools and Tricks for the Applied Analyst](/teaching/stata.qmd)
- [Survey Design](/teaching/surveys.qmd)
- [Survey Experiments](/teaching/sew.qmd)
- [Teaching Workshops & Methods Courses](/teaching/twm.qmd)

# Short Courses (2-5 days)

- [Categorical Data Analysis: Statistical Horizons Seminar](/teaching/cdash.qmd)
- [Data Visualization Using Stata and LLMs: AI Horizons Seminar](/teaching/dvs.qmd)
- [Item Response Theory](/teaching/irt.qmd)
- [Longitudinal Data Analysis: Methodology Center Summer Institute (organizer)](/teaching/mcapsi.qmd) *(next offering July 2027)*
  - [Data Visualization: Understanding Longitudinal Data (instructor)](/teaching/mcapsi.qmd)
  - [Model Visualization: Presenting Longitudinal Results (instructor) ](/teaching/mcapsi.qmd)
  - [Complications with Longitudinal Data Analysis: Nonlinearities, Categorical Outcomes, Moderation, and Mediation (instructor)](/teaching/mcapsi.qmd)
  - [Causal Inference with Longitudinal Data (instructor)](/teaching/mcapsi.qmd)

# Graduate Courses

[**Categorical Data Analysis: Purdue SOC 681**](/teaching/cda.qmd)

- *Topics covered include (by section #):* (01) Introduction and overview of linear regression, (02) Nonlinear effects in linear regression, (03) Models for count dependent variables, (04) Models for binary dependent variables, (05) Zero-inflated count models, (06) Hypothesis testing, model fit, and model diagnostics, (07) Interaction effects and cross-model comparisons of effects, (08) Models for nominal dependent variables, (09) Models for ordinal dependent variables, (10) Bonus hodgepodge: three-way interactions, robust SEs, fractional response models, visualizing distributions, visualizing intersectional effects, etc.

[**Data Visualization: Purdue SOC 681**](/teaching/dataviz.qmd)

- *Topics covered include (by section #):* (01) Introduction, (02) Univariate distributions, (03) Transformations, (04) Stata tools, (05) Plotting parts of a whole, (06) Balance plots, (07) Bivariate relationships, (08) Plotting change over time, (09) General advice for effective graphs, (10) Maps, (11) Model results, (12) Plots of predictions, (13) Marginal effects, (14) Interaction effects, (15) Diagnosing and modeling nonlinearities, (16) Model diagnostics, (17) Miscellaneous advanced topics

 [**Experimental Design: Purdue SOC 609**](/teaching/em.qmd)** **

- *Topics covered include (by section #):* (01) Causality, (02) Validity and design, (03) Lab experiments, (04) Survey experiments, (05) Sampling, (06) Social desirability, (07) Factorial and conjoint experiments, (08) Audit and field experiments,  (09) Power analysis, (10) Analyzing experimental data, (11) Writing about experiments

[**Latent Variable Modeling: Purdue SOC 609**](/teaching/lvm.qmd)

- *Topics covered include (by section #):* (01) Introduction to latent variables, (02) Summated scales, (03) Principal components analysis (PCA) and exploratory factor analysis (EFA), (04) Confirmatory factor analysis (CFA), (05) Item response theory (IRT) and nonlinear factor analysis (NLFA), (06) Latent class analysis (LCA) and latent profile analysis (LPA), (07) Structural equation modeling (SEM), (08) Measurement invariance (MI) and differential item functioning (DIF)

[**Social Psychology: Purdue SOC 609**](/teaching/spgrad.qmd)

- *Topics covered include (by section #):* (01) Theory building, (02) Symbolic interactionism, (03) Identity theory, (04) Social identity theory, (05) Group position model, (06) Stereotypes, (07) Cognition and Bias, (08 - 09) Status characteristics theory, (10) Stigma and labeling, (11) Health and illness, (12) Exchange theory, (13) Emotions, (14 - 15) Affect control theory, (16) Cooperation

# Undergraduate Courses

[**Social Psychology: Purdue SOC 340**](/teaching/spug.qmd)

- *Topics covered include:* Theory, Methods, Symbolic Interactionism, The Self, Social Roles, Identity  Theory, Social Identity  Theory, Group Position Model, Small Groups, Status, Status Beliefs, Status Construction, Status Interventions, Well-Being, Stereotypes, Cognition, Bias, Attitude Change, Emotions, Affect, Cooperation

# Miscellaneous 

- [Discrete Choice Analysis: What Our Choices Reveal about Preferences, Tradeoffs, and Alternatives (Statistical Horizons blog post)](https://statisticalhorizons.com/discrete-choice-analysis-what-our-choices-reveal-about-preferences-tradeoffs-and-alternatives/)
- [Making Predictions that Match Causal Questions](/teaching/pred.qmd)
- [Organizing Your Research Workflow: Tips & Tricks](https://drive.google.com/file/d/1KtDCTD6125pRt8yTAgD0UKbsmssMB1rd/view?usp=sharing)
- [ASA Data Visualization Workshop: Flexible Approaches for Assessing and Modeling Nonlinearities](/teaching/nonlinear.qmd)
- [Linear Regression / Introduction to Quantitative Data Analysis: Indiana University](https://drive.google.com/drive/folders/0B0zgYvK2kIGgfmx3djM4VURuM2VYUEQ1b3BERnluVzBiMDZyd3ZfX1VTdDJxVXZQZmIxOWs?resourcekey=0-mzWGpMuLV1LIpuS5wHOQ1Q&usp=sharing)
