---
title: "Benard, Berg, and Mize 2017 SPQ"
toc: false
---

## Benard, Stephen, Mark T. Berg, and Trenton D. Mize. 2017. "Does Aggression Deter or Invite Reciprocal Behavior? Considering Coercive Capacity." *Social Psychology Quarterly.*

- [Link to PDF](https://drive.google.com/file/d/1KO0WdO8cs0agu-JrIWWm6f_74rai2TY4/view?usp=sharing)
- [Link to article on journal's site](http://journals.sagepub.com/doi/full/10.1177/0190272517728904)
- [Online Appendix](https://drive.google.com/open?id=1wThaMV5T7R6WfFIZMrTY5BvVGqDCl_dl)
- [Replication Files](https://scholarworks.iu.edu/dspace/handle/2022/21709)

\- Abstract: How do people respond to aggression? Theory differs on whether aggressive behavior deters antagonists or provokes retaliation, and the empirical evidence is mixed. We bridge contradictory findings in the literature by identifying a previously unexamined moderating variable: the extent to which individuals can increase their coercive capability (which we call “escalating”). We argue that when escalating is costly, aggression deters potential antagonists. In contrast, when escalating is less costly, behaving aggressively fails to deter aggressive partners. We test these predictions in two behavioral experiments that manipulate the cost of escalating and whether interaction partners are aggressive or deferential. We find support for deterrence predictions when escalating is either high or low cost, but not when it is medium cost. Taken together, we provide evidence that the cost of escalation plays a key role in decisions about aggression.***  ***
