---
title: "Benard and Mize 2016 HCST"
toc: false
---

## Benard, Stephen and Trenton D. Mize. 2016. "Small Groups: Reflections Of, and Building Blocks For Social Structure." in the *Handbook of Contemporary Sociological Theory*. Springer.

- [Link to PDF ](https://drive.google.com/file/d/1SM6dT0IK4x4l1bV7yDp3_ELjfuvCrFGR/view?usp=sharing)
- [Link to Handbook's Website](http://www.springer.com/us/book/9783319322483)

\- Abstract: Our lives are tightly bound up in small groups. From families, friends, and peer groups, to athletic teams, voluntary associations, and work units, small groups constitute much of the fabric of our daily lives. In this chapter, we argue that small groups are important for sociologists to understand because they serve as building blocks of society, offering settings in which rudimentary forms of social structure can emerge. Small groups provide a place – usually the first place – where individuals learn to negotiate hierarchies, conform to or deviate from social norms, develop group boundaries, and where they develop and disseminate bits of culture. We organize the chapter around these five structure-producing social processes: status, power, identity, influence and social norms, and group cultures, and illustrate how these processes operate in small groups. In doing so, we illustrate the diversity of theories that have focused on small groups as the unit of analysis. We also speculate about the reasons why sociological interest in small groups has declined over time, and suggest ways in which small groups researchers can further contribute to and play a larger role in sociology.
