---
title: "Doan and Mize 2020 SocSci"
toc: false
---

## Doan, Long and Trenton D. Mize. 2020. "Sexual Identity Disclosure among Lesbian, Gay, and Bisexual Individuals." *Sociological Science.*

- [Link to PDF](https://drive.google.com/file/d/1FxvrploAS28wvGwIsR-6p8umaCSzYrwG/view?usp=sharing)
- [Link to article on journal's site](https://sociologicalscience.com/articles-v7-21-504/)
- [Online Supplement](https://drive.google.com/file/d/1_gMrjIjtyTufUeMG2ey5hpp5BMyBCPrU/view?usp=sharing)
- [Replication files](https://drive.google.com/drive/folders/1uddR4Vhm2LRIdHfpl_ghVGqxhTbKg1w7?usp=sharing)

\- Abstract: Most research on sexual prejudice explicitly or implicitly assumes that an individual’s sexual orientation identity is known to observers. However, there has been little large-scale survey evidence examining differential rates of disclosure among lesbian, gay, and bisexual (LGB) individuals, and there remains much to be studied as to why and when LGB individuals choose to disclose their sexual identity to others. Using data from a nationally representative sample of LGB Americans (N=1,085), we assess the contexts and conditions under which LGB individuals disclose their sexual identities. Results show that bisexual women and men are significantly less likely to disclose their sexual identity across several important social domains, such as family and the workplace. This disclosure gap is partially explained by measures of identity commitment but surprisingly not by measures of perceived social acceptance. We discuss implications of these findings for sexuality and identity research.
