---
title: "Manago, Mize, and Doan 2022 SM"
toc: false
---

## Manago, Bianca, Trenton D. Mize, and Long Doan. 2021. “Can you really study an army on the internet? Comparing how status tasks perform in the laboratory and online settings.” *Sociological Methodology.*

- [Link to PDF](https://drive.google.com/file/d/1gxbf2uQUMIx0bv73L-0dHvkWyul2Me7D/view?usp=sharing)
- [Link to article on journal's site](https://doi.org/10.1177%2F00811750211014242)
- [Replication Files](https://github.com/biancamanago/SCTOnlineTasks)

\- Abstract: Laboratory experiments have a long history within sociology, with their ability to test causality and their utility for directly observing behavior providing key advantages. One influential social psychological field, status characteristics and expectation states theory, has almost exclusively used laboratory experiments to test the theory. Unfortunately, laboratory experiments are resource intensive, requiring a research pool, laboratory space, and considerable amounts of time. For these and other reasons, social scientists are increasingly exploring the possibility of moving experiments from the lab to an online platform. Despite the advantages of the online setting, the transition from the lab is challenging, especially when studying behavior. In this project, we develop methods to translate the traditional status characteristics experimental setting from the laboratory to online. We conducted parallel laboratory and online behavioral experiments using three tasks from the status literature, comparing each task’s ability to differentiate on the basis of status distinctions. We find the tasks produce equivalent results in the online and laboratory environment; however, not all tasks are equally sensitive to status differences. Finally, we provide more general guidance on how to move vital aspects of laboratory studies, such as debriefing, suspicion checks, and scope condition checks, to the online setting.
