---
title: "Manago and Mize 2022 SSR"
toc: false
---

## Manago, Bianca and **Trenton D. Mize**. 2022. “The status and stigma consequences of mental illness labels, deviant behavior, and fear.” *Social Science Research.*

- [Link to PDF](https://drive.google.com/file/d/12fuGkXBaAGzM9FrxF3xW-koK9fu9bOcI/view?usp=sharing)
- [Link to article on journal's site](https://doi.org/10.1016/j.ssresearch.2021.102690)
- [Online Appendix](https://drive.google.com/file/d/1CzAL47Fl1nOKlDMejAYzUkshvnAzk-H1/view?usp=sharing)
- [Replication files](https://github.com/biancamanago/mtc_2022_SSR_replication-files)

\- Abstract: Despite the breadth of research on mental illness, there remains some ambivalence about the distinct and combined effects of mental illness labels and deviant behavior for stigma and status. To examine the effects of mental illness labels and deviant behavior on stigma and status, we use experimental methods. Because fear is tightly linked with understandings of mental illness, we also consider the role of fear in these processes. We find that absent behavioral descriptions, mental illness labels do not affect status; however, deviant behavior that is and is not labeled as a mental illness decreases status. Neither deviant behavior nor mental illness labels independently affect stigma; however, compared to unlabeled deviant behavior, deviant behavior that is labeled as a mental illness either increases or decreases stigma for fear-inducing and fear-neutral behavior, respectively. In summary, the effects of mental illness labels appear to depend on behavioral connotations, including fear.
