---
title: "Manago and Mize 2024 Socius"
toc: false
---

## Manago, Bianca and Trenton D. Mize. 2024. “What is the effect of an inferred mental illness label on stigma? Theoretical and empirical challenges.” *Socius.*

- [Link to PDF](https://drive.google.com/file/d/1mCq2Msxpf7S3aIX2H3R2vtA7y7A36k7p/view?usp=sharing)
- [Link to article on journal's website](https://doi.org/10.1177/23780231241274237)
- [Replication files](https://github.com/biancamanago/mls_2024_socius_replicationFiles)
- [Online Appendix](https://drive.google.com/file/d/128AGhpDBnCVetXbPwWO_rBOuSN6x9xzc/view?usp=sharing)

### Abstract

One of the strengths of vignette-based experimental research is that it captures the mental illness labeling process in the way it often occurs – inference without full information. Unfortunately, since the process of inferring a label is associated with confounding variables, e.g. perceived deviance and prior contact, it is difficult to measure the causal effect of inferred mental illness labels. To address these confounding variables, we advocate for the use of causal inference methods. Using causal inference methods, we analyze the 1996, 2006, and 2018 General Social Survey National Stigma Studies. We find that: (1) an inferred mental illness label affects desired social distance, (2) the likelihood and effect of labeling differs across mental illnesses, and (3) causal inference methods that exact match on contact better approximate the causal effect of labeling. These findings underline the importance of clearly identifying effects of interest and causal methods’ utility for estimating these effects.
