---
title: "Mize 2016 ASR"
toc: false
---

## Mize, Trenton D. 2016. "Sexual Orientation in the Labor Market." *American Sociological Review.*

- [Link to PDF](https://drive.google.com/file/d/1qIoRW-hCMZw2yMzZMdroG_18OKWZAClH/view?usp=sharing)
- [Link to article on journal's site](http://asr.sagepub.com/content/early/2016/10/24/0003122416674025.full.pdf+html)
- Media Coverage: [Bloomberg](http://www.bloomberg.com/news/articles/2016-11-18/there-s-a-bisexual-wage-gap-too), [NBC News](http://www.nbcnews.com/feature/nbc-out/bisexual-workers-earn-less-straight-gay-counterparts-study-n686081), [TIME](http://motto.time.com/4578396/bisexual-wage-gap-money/), [Herald-Times](http://www.heraldtimesonline.com/news/local/study-finds-pay-gap-between-bisexual-straight-workers/article_948c549b-8649-51b0-964d-51be99467373.html), [Indiana University](http://news.indiana.edu/releases/iu/2016/11/bisexual-pay-gap.shtml), [Indiana Daily Student](http://www.idsnews.com/article/2016/12/iu-study-finds-bisexuals-are-subject-to-wage-gap), [HR Dive](http://www.hrdive.com/news/study-bisexual-employees-earn-less-than-heterosexuals-in-similar-jobs/430624/), [LGBTQ Nation](http://www.lgbtqnation.com/2016/11/wage-gap-bisexual-employees-make-less-straight-coworkers/), [Politico](http://www.politico.com/tipsheets/morning-shift/2016/11/texas-judge-considers-overtime-rule-217443), [LGBT Weekly](http://lgbtweekly.com/2016/11/16/new-study-shows-bisexual-men-and-women-face-pay-gap/), [Parents.com](https://www.parents.com/parenting/money/lgbtq-equal-pay-day-wage-gap/)
- [Podcast About the Article](http://asr.sagepub.com/site/misc/Index/Podcast.xhtml)
- [Online Appendix](https://drive.google.com/file/d/0B0zgYvK2kIGgOG5WUE1GVDc3UW8/view?usp=sharing&resourcekey=0-CGfxoj5Y1dGCwkPLQv6Clg)
- [Replication Files](https://drive.google.com/drive/folders/0B0zgYvK2kIGgQzVVWFoxMUo2TGs?resourcekey=0-ZPKQNJyHsUJsRaMecmxvTA&usp=sharing)

\- Abstract: Most analyses of sexual orientation and earnings find that gay men face a wage gap, whereas lesbian women earn higher wages than similar heterosexual women. However, analyses rarely consider bisexual men and women as a unique group separate from other sexual minorities. I argue that such binary views of sexual orientation—treating sexual minorities as a homogenous non-heterosexual group—have obscured understandings of the impact of sexual orientation on labor market outcomes. Specifically, I predict that unequal outcomes for gay men and lesbian women are partly due to the influence of family arrangements and their effects on earnings. In contrast, I argue that bisexual men and women should be the most disadvantaged in the labor market, due to particularly disadvantaging stereotypes, perceptions of choice to their sexual orientation, and prejudicial treatment. Using data from the General Social Survey (*N* = 13,554) and the National Longitudinal Study of Adolescent to Adult Health (*N* = 14,714), I show that family arrangements explain some of the observed earnings differentials for gay men and lesbian women. Bisexual men and women, in contrast, face wage penalties that are not explained by human capital differences or occupational characteristics. Perceptions of prejudicial treatment partially explain the observed wage gaps.
