---
title: "Mize, Kaufman, and Petts 2021 Socius"
toc: false
---

## Mize, Trenton D., Gayle Kaufman, and Richard J. Petts. 2021. "Visualizing Shifts in Gendered Parenting Attitudes during COVID-19." *Socius*.

- [Link to PDF](https://drive.google.com/file/d/1BSMbxgeGuwh4y8VOtBfITz4ZgO-pzn4d/view?usp=sharing)
- [Link to article on journal's site](https://doi.org/10.1177%2F23780231211013128)
- [Online Supplement](https://drive.google.com/file/d/1mj2TIDRP1LYp_-kFnNxjjsEYYJtBo9lE/view?usp=sharing)
- [Replication files](https://drive.google.com/drive/folders/1OXVbbBtkpAx6V32ktpJ5fY2v4d0vdBam?usp=sharing)
- Media Coverage: [Vox](https://www.vox.com/recode/22568635/women-remote-work-home), [PsyPost](https://www.psypost.org/2021/07/the-covid-19-pandemic-has-spurred-a-shift-toward-more-traditional-beliefs-about-mother-and-father-roles-study-suggests-61600), [Forbes](https://www.forbes.com/sites/lizelting/2021/08/12/the-next-lockdown-doesnt-have-to-deepen-the-she-cession-this-time-we-can-be-ready/?sh=63436b21f1c2)

\- Abstract: Many scholars have expressed fears that the 2019 coronavirus pandemic may exacerbate gender inequalities. Indeed, studies have suggested that women, and mothers in particular, have been particularly affected by reducing their participation in the paid labor market to meet increased caregiving needs. What is less clear is whether the pandemic has also shifted attitudes about mothers’ and fathers’ roles. We collected data on gendered parenting attitudes both before and during the pandemic and report shifts in attitudes in this data visualization. Consistent with fears of exacerbated gender inequality, we find a shift toward more conventional gender parenting attitudes. We also find an increase in the importance placed on mothers’ and fathers’ earning money and a decrease in the role mothers and fathers play in child development, both of which may be due to the pandemic’s effects on the economy and schooling.
