---
title: "Mize and Han 2025 Sociological Science"
toc: false
---

## **Mize, Trenton D.** and Bing Han. 2025. "Inequality and total effect summary measures for nominal and ordinal variables." *Sociological Science.*

- [PDF of article](https://drive.google.com/file/d/1DEW-mmC_NF6sj8eu2dRW8XWjdUceYpPX/view?usp=sharing)
- [Link to article on journal's website](https://sociologicalscience.com/articles-v12-7-115/)
- [Replication files](https://drive.google.com/drive/folders/1f7gzbjxIsqytjaXGW1iTULz4Im7Bc4PY?usp=sharing)

### Stata Commands

Two companion Stata commands implement the methods shown in the article:

- [`meinequality` for marginal effect inequality statistics](/software/meinequality/index.qmd)
- [`totalme` for total marginal effect estimates](/software/totalme/index.qmd)

For most cases, we recommend using the commands linked to immediately above to implement our methods and following the examples shown at those links. However, we also provide the original example files here if useful:

- [Stata do-files](https://drive.google.com/drive/folders/1UBDtIxub9hr__PMdSiy8eWnhVT00WQyg?usp=sharing)

### R Implementation

The [`marginaleffects`](https://marginaleffects.com/) package in R now has built-in capabilities to automate the calculation of ME inequality and total ME. See examples here: 

- [marginaleffects.com/bonus/total_marginal_effect](https://marginaleffects.com/bonus/total_marginal_effect.html)

For most cases, we recommend using the package linked to immediately above to implement our methods and following the examples shown at that link. However, we also provide the original example files here if useful:

- [R script files](https://drive.google.com/drive/folders/1e0vT2k67XJ6QD7unWxmy3btUuJmqA4mm?usp=sharing)

### Abstract

Many of the topics most central to the social sciences involve nominal groupings or ordinal rankings. There are many cases in which a summary of a nominal or ordinal independent variable’s effect, or the effect on a nominal or ordinal outcome, is needed and useful for interpretation. For example, for nominal or ordinal independent variables a single summary measure is useful to compare effect sizes of different variables in a single model or to compare effect sizes across multiple models, as with mediation. For nominal or ordinal dependent variables, there are often an overwhelming number of effects to examine and understanding the holistic effect of an independent variable, or how effect sizes compare within or across models is difficult. In this project, we propose two new summary measures using marginal effects (MEs). For nominal and ordinal independent variables, we propose *ME inequality* as a summary measure of a nominal or ordinal independent variable’s holistic effect. For nominal and ordinal outcome models, we propose a *total ME* measure which quantifies the comprehensive effect of an independent variable across all outcome categories. The added benefits of our methods are both intuitive and substantively meaningful effect size metrics and approaches that can be applied across a wide range of models, including linear, nonlinear, categorical, multilevel, longitudinal, and more.
