---
title: "Mize and Han UDMDA"
toc: false
---

## **Mize, Trenton D. and Bing Han. Forthcoming. "Marginal effects:   A flexible method for substantively meaningful interpretations across linear and nonlinear models" in *Understanding Data Modeling and Data Analysis*. Edward Elgar Publishing.**

- [Link to PDF (accepted manuscript)](https://drive.google.com/file/d/1QOpdFeYZpWHwBx88RW7p8vHeCq4egp7P/view?usp=sharing)
- Link to chapter on handbook's website
- [Example Stata Files](https://drive.google.com/drive/folders/1twFyzsi3x4XnYvuDiLjxCJtM7JqYLtXa?usp=sharing)
  - We recommend using the [`mecompare` command](/software/mecompare/index.qmd) to automate calculation of effects shown in the chapter.
- [Example R Files](https://drive.google.com/drive/folders/1eqLCd_deKz8Cdi4dy-OH8kPWP0qdOPhU?usp=sharing)
  - We recommend using the [marginaleffects package in R](https://marginaleffects.com/) to automate calculation of effects shown in the chapter.

### Abstract

Marginal effects have become a widely used tool to understand the results of regression models. Marginal effects have many advantages over coefficient-based interpretations as they can be easily expressed in the metric of key interest, are easy to interpret, are flexible, avoid issues with the coefficients in categorical outcome models, and provide a single coherent framework for interpretation across many different types of models. Contemporary software in Stata and R makes it possible to use marginal effects for interpretation with almost any regression model. In this chapter, we first provide an accessible overview of marginal effects and show how they are calculated in linear, nonlinear, and categorical outcome models. We discuss the myriad of options an analyst has for marginal effects interpretations, including common summary methods. We then summarize how marginal effects can be used for specific purposes such as for tests of interaction/moderation and for tests of cross-model comparisons such as mediation. We close with a discussion of various advanced topics that have received limited attention such as using marginal effects in multilevel and longitudinal models, summarizing nominal independent variables’ effects, and group comparisons.
