---
title: "Mize, Doan, and Long 2019 SM"
toc: false
---

## Mize, Trenton D., Long Doan, and J. Scott Long. 2019. "A General Framework for Comparing Predictions and Marginal Effects Across Models." *Sociological Methodology.*

- [Link to PDF](https://drive.google.com/file/d/186AeIPGoqgXmhFvVfKD5N_LP2xF6_YjG/view?usp=sharing)
- [Link to article on journal's site](https://journals.sagepub.com/doi/full/10.1177/0081175019852763)
- [Stata package `mecompare` which automates calculation of cross-model comparisons of marginal effects](/software/mecompare/index.qmd)
  - For most all applications, we recommend using `mecompare`. 
  - However, if you want to do things the hard way, the original [template do-files to recreate examples in the paper](/research/mize_doan_long_2019_SM/mecompare_exs.qmd) remain available.
- [Replication Files](https://drive.google.com/open?id=18RS5C47b_ddGaRRXILfmxmfOB41AyA7D) (more complicated; for advanced users)
- [Graphs and GIFs illustrating cross-model covariances of effects](/research/mize_doan_long_2019_SM/gifs.qmd)

### Stata command

A companion Stata command that implements all methods shown in the article is available:

- [`mecompare` for cross-model comparisons of marginal effects](/software/mecompare/index.qmd)

An R package that implements the same framework is also available:

- [`suest` for cross-model comparisons of predictions and marginal effects in R](/software/suest_r/index.qmd)

### Abstract

Many research questions involve comparing predictions or effects across multiple models. For example, it may be of interest whether an independent variable’s effect changes after adding variables to a model. Or, it could be important to compare a variable’s effect on different outcomes or across different types of models. When doing this, marginal effects are a useful method for quantifying effects since they are in the natural metric of the dependent variable and they avoid identification problems when comparing regression coefficients across logit and probit models. Despite advances that make it possible to compute marginal effects for almost any model, there is no general method for comparing these effects across models. In this paper we provide a general framework for comparing predictions and marginal effects across models using seemingly unrelated estimation to combine estimates from multiple models, which allows tests of the equality of predictions and effects across models. We illustrate our method to compare nested models, to compare effects on different dependent or independent variables, to compare results from different samples or groups within one sample, or to assess results from different types of models.
