---
title: "Mize and Manago 2018 SCur"
toc: false
---

## Mize, Trenton D. and Bianca Manago. 2018. "The Stereotype Content of Sexual Orientation." *Social Currents.*

- [Link to PDF](https://drive.google.com/file/d/1_a3yTQwBZRmWtE5npthXx7qB_i-o0lNg/view?usp=sharing)
- [Link to article on journal's site](http://journals.sagepub.com/doi/full/10.1177/2329496518761999)
- [Online Appendix](https://drive.google.com/open?id=18YEFLI_Q37CzdkL-OXStIg5RcZhZfnrp)
- [Replication Files](https://drive.google.com/open?id=1kN4dARIY8mEQYJphIfYXgVBNsrG54C1p)

\- Abstract: The stereotype content model provides a powerful tool to examine influential societal stereotypes associated with social groups. We theorize how stereotypes of gender, sexuality, and a group’s status in society combine to influence societal views of sexual orientation groups—placing particular emphasis on stereotypes of warmth and competence. In two survey experiments we collect quantitative measures of stereotype content and open-response items on the stereotypes of bisexual individuals. We predict—and find—that gay men and lesbian women face disadvantaging stereotypes; bisexual men and women however, face the most severely negative stereotypes of any sexual orientation group—with aggregate judgments of low warmth and competence. In the second study, using a diverse sample, we show that stereotypes about sexual orientation groups are largely culturally consensual. We conclude by emphasizing the importance of comparative approaches that consider both advantaged and disadvantaged groups to fully contextualize stereotypes of minority groups.
