---
title: "Mize 2024 Socius"
toc: false
---

## Mize, Trenton D. 2024. “Divergence and convergence across presumed and actual stereotypes.” *Socius.*

- [Link to PDF](https://drive.google.com/file/d/16p0l_0P85NwEsXShTHqGaNTX0hju6svF/view?usp=sharing)
- [Link to article on journal's website](https://doi.org/10.1177/23780231241286873)
- [Replication files](https://drive.google.com/drive/folders/1kI9PUv2IRJ40tw7hNkrzKIRTlCANawGm?usp=sharing)
- [Online appendix](https://drive.google.com/file/d/14SGxdbaSZrGfUMp_9UdboPcUKbn1hRB8/view?usp=sharing)

### Abstract

Stereotypes are foundational to social life, with warmth and competence key to views of social groups. Some theoretical and empirical work on stereotypes focuses on personal “first order” beliefs about social groups. Other work focuses on perceptions of a culture’s stereotypes, or “generalized second order” beliefs. Scholars differ in which they consider more impactful or whether they think they are unique or represent the same underlying belief. In this visualization, I present data from a large online survey experiment (*N* = 1045) where participants reported either first or generalized second order stereotypes about 19 different social groups. For the majority of stereotypes measured, the results differ across the two methods with perceptions of culture more pessimistic than people’s actual first order beliefs would suggest. That is, people tend to assume others hold more negative stereotypes than they actually do—and this is especially pronounced for negatively viewed social groups.
