---
title: "Mize Forthcoming"
subtitle: "Social Psychology Quarterly"
toc: false
---

## Mize, Trenton D. Forthcoming. “Competence perceptions at the intersection of gender and race-ethnicity.” *Social Psychology Quarterly.*

- [Link to PDF](https://drive.google.com/file/d/1rwQ7BU-MajUJ8ty-I8RzSGirNvbRMd4t/view?usp=sharing)
- [Link to article on journal's website](https://doi.org/10.1177/01902725241289875)
- [Replication files](https://drive.google.com/drive/folders/11Cc4LUSCvsvwkHKrReNp8OQ64sj9OL6a?usp=sharing)
- [Online Appendix](https://drive.google.com/file/d/1s8NSZN-88WY9wQ4m2l5Kjm4OthcvZr0f/view?usp=sharing)

### Abstract

Competence perceptions represent a fundamental dimension of human perception and have wide-ranging consequences for social interaction. Therefore, it is no surprise that multiple prominent social psychological theories emphasize the role of competence perceptions. We know that both a person’s gender and their race-ethnicity influence assumptions about their competence, but we have only a few studies examining the intersections of these factors. Using a large survey experiment (*N* = 1,219), I examine competence perceptions at the intersection of 2 gender and 13 racial-ethnic categories. Results show large effects of both gender and race-ethnicity and also highly intersectional stereotypes, i.e., there is no one overarching effect of gender or race-ethnicity but instead contingent effects. By oversampling racial-ethnic minorities, I also test the assumption of consensus for competence perceptions. Results show highly consensual perceptions, suggesting we all recognize society’s stereotypes even if we don’t agree with them.
