---
title: "Mize and Myers 2011 JURO"
toc: false
---

## Mize, Trenton D. and Tre Myers. 2011. "Exploring Racial Differences on the Measurement and Experience of Emotion." *Journal for Undergraduate Research Opportunities.*

- [Link to PDF of Article](https://drive.google.com/file/d/1CuwIkrWe91lwjfC-ngyxA2f4vDb1jqvF/view?usp=sharing)
- [Link to article on journal's site](http://juro.uga.edu/index.html)

\- Abstract: An emerging technique for studying emotions in social interaction involves the measurement of temperature changes in regions of the face using infrared thermography. In this paper, we explore possible systematic differences in facial temperature, facial temperature changes, and self-reported emotion as a function of participant’s racial identification and skin tone color. In an experimental study, participants viewed emotionally evocative images while their facial temperature was measured using infrared thermography. Participants also completed self-report emotion measurements. We found consistent differences in average facial temperature by race across all images and all facial regions, but no differences in facial temperature change based on race (indicating no differences in the experience of emotion by race). We also found some minor differences in self-reported emotion by race, but no differences that would explain the consistent average temperature differences observed. We propose that the facial temperature differences observed were due to different skin tone emissivities, which would cause lighter or darker skin tones to be measured at different temperatures by the infrared camera. This explanation was supported as skin tone was more predictive of mean facial temperature than was self-reported race. We close by discussing the important implications the findings have for future studies using infrared thermography to measure emotion.
