---
title: "Mize 2015 SocComp"
toc: false
---

## Mize, Trenton D. 2015. "What Social Psychology Can Contribute to the Study of Sex, Gender, and Sexual Orientation." *Sociology Compass.*

- [Link to PDF](https://drive.google.com/file/d/1q3fxL5u5wICD_K6Bav0fuXxhPLL_IIsG/view?usp=sharing)
- [Link to article on journal's site](http://onlinelibrary.wiley.com/doi/10.1111/soc4.12331/abstract)

\- Abstract: The concepts of sex and gender have received increasing attention in sociology in recent years, with social psychologists providing many of the key insights. Issues of sexual orientation and sexuality have received comparably less attention, although many of the tools social psychologists use could be fruitfully applied to better understand sex, gender, sexual orientation, and the intimate connections between the three. In particular, I outline the perspectives of doing gender, stereotyping, and status and suggest possible ways to incorporate these frameworks into intersectional examinations of sex, gender, and sexual orientation. I argue that to fully understand sex, gender, or sexual orientation, researchers should consider all three and recognize the highly interconnected nature of each.
