---
title: "Mize and Manago 2018 ASR"
toc: false
---

## Mize, Trenton D. and Bianca Manago. 2018. "Precarious Sexuality: How Men and Women are Differentially Categorized for Similar Sexual Behavior." *American Sociological Review.*

- [Link to PDF](https://drive.google.com/file/d/1gdjuMsjdZ7An9M8aeYMaqHfcXFEl0Vwj/view?usp=sharing)
- [Link to article on journal's site](http://journals.sagepub.com/doi/full/10.1177/0003122418759544)
- [Online Appendix](https://drive.google.com/open?id=1Y6dM3XiNN0-eG1ai51Mb2diXUQUtEnCf)
- [Replication Files](https://drive.google.com/open?id=1FNN2Yk0a4kMxOQpQW5Wc04FnvXgcUrTT)

\- Abstract: Are men and women categorized differently for similar sexual behavior? Building on theories of gender, sexuality, and status, we introduce the concept of precarious sexuality to suggest that men’s—but not women’s—heterosexuality is an especially privileged identity that is easily lost. We test our hypotheses in a series of survey experiments describing a person who has a sexual experience conflicting with their sexual history. We find that a single same-sex sexual encounter leads an observer to question a heterosexual man’s sexual orientation to a greater extent than that of a heterosexual woman in a similar situation. We also find that a different-sex sexual encounter is more likely to change others’ perceptions of a lesbian woman’s sexual orientation—compared to perceptions of a gay man’s sexual orientation. In two conceptual replications, we vary the level of intimacy of the sexual encounter and find consistent evidence for our idea of precarious sexuality for heterosexual men. We close with a general discussion of how status beliefs influence categorization processes and with suggestions for extending our theoretical propositions to other categories beyond those of sexual orientation.
