---
title: "Mize 2017 SSM"
toc: false
---

## Mize, Trenton D. 2017. "Profiles in Health: Multiple Roles and Health Lifestyles in Early Adulthood." *Social Science & Medicine.  *

- [Link to PDF](https://drive.google.com/file/d/1WYzyFYR_YVv6qGDXE3Yat8AwTheKJ1py/view?usp=sharing)
- [Link to article on journal's site](http://www.sciencedirect.com/science/article/pii/S0277953617301065)
- [Online Appendix](https://drive.google.com/file/d/0B0zgYvK2kIGgUE1kVDducV9PT2s/view?usp=sharing&resourcekey=0-fmR9FGqxtAYWsN1GID5XgQ)
- [Replication Files](https://drive.google.com/drive/folders/1CUeDcav6-_S1pz5GMuLsaXyrVTMCP55b?usp=sharing)

\- Abstract: *Rationale*: Despite theoretical work suggesting that health behaviors should be considered in tandem rather than as individual and disconnected practices—little quantitative work has examined lifestyles of health behavior practices. In addition, while much work has examined the association of holding multiple social roles and health outcomes, little work has examined how acquiring multiple roles in early adulthood influences health behavior. *Objective:* This article (a) illustrates the utility of examining health lifestyles—defined as constellations of individual health behavior practices—and (b) contributes to the literature on how accumulating multiple social roles is associated with health. *Methods:* Using two waves of the National Longitudinal Study of Adolescent to Adult Health (N=12,098) a structural equation modeling approach is used to both (a) model latent health lifestyles from observed health behavior indicators, and (b) to predict health lifestyle membership based on changes in role-occupancy during the transition to early adulthood. *Results:* Results suggest that the type of social role matters, with intensive obligatory roles associated with lifestyles of less tobacco, alcohol, and marijuana use but also with physical inactivity. In contrast, voluntary roles are associated with more active lifestyles but increased alcohol use. *Conclusion:* The results illustrate the importance of modeling overall health lifestyles rather than focusing only on individual health behaviors and also advance our understanding of how holding multiple roles is associated with health by extending the framework to an examination of health behavior.
