---
title: "Mize and Kincaid 2025"
subtitle: "American Sociological Review"
toc: false
---

## Mize, Trenton D. and Reilly Kincaid. 2025. “Role-accumulation and mental health across the life course.” *American Sociological Review.*

- [Link to PDF](https://drive.google.com/file/d/1_CtkNXK_GAc7htCTRPKJCsdP-TwlrWql/view?usp=sharing)
- [Link to article on journal's website](https://doi.org/10.1177/00031224241313394)
- [Replication files](https://drive.google.com/drive/folders/1ZL8kHQJOGxZzSmD6_Sj2Oqyagh7zhBCw?usp=sharing)
- [Online Appendix](https://drive.google.com/file/d/1Lz8_xg7U3cIzDvYl36f2fA6x1ZAR2pgS/view?usp=sharing)

### Abstract

Decades of research shows that the accumulation of social roles leads to better mental health and well-being overall, but role accumulation theory has not proposed or considered heterogeneous effects at different stages in the life course. Rather, social roles’ positive influence on mental health is assumed to be “age agnostic.” In addition, the theory suggests accumulating voluntary roles in particular is the best strategy for mental health, regardless of age. In contrast, socioemotional selectivity theory—an influential theory that covers many similar issues but has not been considered in the role-accumulation literature—suggests that older adults tend to shed peripheral roles such as voluntary ones as a strategy to maximize mental health later in life. Using 21 waves/years of longitudinal data (*N* = 15,099), we examine the effect of role-accumulation across the entire adult life course. We use fixed effects models to better approximate the causal effect of role-accumulation on mental health and find that the types of roles matter, with obligatory role-accumulation associated with better mental health at most ages, but not in late adulthood. In contrast, we find that voluntary role-accumulation is beneficial at all ages, and especially for the mental health of older adults—supporting role-accumulation theory predictions.
