---
title: "Mize 2019 SocPro"
toc: false
---

## Mize, Trenton D. 2019. "Doing Gender by Criticizing Leaders: Public and Private Displays of Status." *Social Problems.*

- [Link to PDF](https://drive.google.com/file/d/1eXw95sKmjZPyDVKtXEkXLJB8FnFjh71R/view?usp=sharing)
- [Link to article on journal's site](https://academic.oup.com/socpro/advance-article-abstract/doi/10.1093/socpro/spx032/4741338?redirectedFrom=fulltext)
- [Online Appendix](https://drive.google.com/open?id=1Q1rfxYIHuRdDLkSmAk5HjVAAZPpi4EdK)
- [Replication Files](https://drive.google.com/open?id=1f6biTN39YHiXDHBHobg2XQCOvBWiQ-9n)

\- Abstract: Previous work shows that stereotypes influence women’s ability to attain and act in leadership positions, however much less work has examined the role that gendered expectations and stereotypes might play for subordinate behavior and how this might reinforce the gender leadership gap. Drawing on theories of gender and status, I predict gender differences in responses to and behavior in subordinate roles. In a series of experimental studies I find that men are more publicly critical of leaders and are more willing to undermine leaders than are women. In two studies I show that men are more publicly critical in both high and low status subordinate roles, and under both men and women leaders. In a third study, I show that men and women do not differ in their private evaluations of a leader and that gender differences only arise in publicly visible evaluations and criticism. Gender differences in public criticism may be due to men exaggerating their criticism to restore a threatened sense of status or masculinity, or due to women tempering their criticism due to gender stereotypes that discourage assertive and critical behavior for women. Either explanation suggests that men and women perform gendered expectations in public and behave in ways that can disadvantage women leaders.
