---
title: "Mize 2019 Sociological Science"
toc: false
---

## Mize, Trenton D. 2019. "Best Practices for Estimating, Interpreting, and Presenting Nonlinear Interaction Effects." *Sociological Science.*

- [Link to PDF](https://drive.google.com/file/d/1x-ENqBfebAu8vIc7sJW55GFYP-0Hq2AY/view?usp=sharing)
- [Link to article on journal's site](https://www.sociologicalscience.com/articles-v6-4-81/)
- The [`mecompare` command](/software/mecompare/index.qmd) automates all of the tests described in the article. Navigate to the ["Interactions: Mize (2019)" subpages](/software/mecompare/interactions/index.qmd) to see how to replicate all of the article's examples using `mecompare`.
  - The [original template files](https://drive.google.com/open?id=1D2FmhncUONVIYuK6tTgenGIRZn48x-dF) can still be acessed if you want to do things the slightly harder way.
- [Template R script files](https://drive.google.com/drive/folders/1kCpNX-hRSqlbAO-1H_yHtnudqEvJyHn2?usp=sharing)
- [Replication Files](https://drive.google.com/open?id=1fhGTY-BYibCoBBjnJuGtpylU25CZ24xs)

### Stata graphics scheme

The Stata graphics scheme used in the article is available:

- [`cleanplots` Stata graphic scheme](/software/cleanplots/index.qmd)

The same scheme is now available for R's ggplot2:

- [`cleanplots` R graphics theme](/software/cleanplots_r.qmd)

### Abstract

Many effects of interest to sociologists are nonlinear. Additionally, many effects of interest are interaction effects—that is, the effect of one independent variable is contingent on the level of another independent variable. The proper way to estimate, interpret, and present these two types of effects individually are well known. However, many analyses that combine these two—that is, tests of interaction when the effects of interest are nonlinear—are not properly interpreted or tested. The consequences of approaching nonlinear interaction effects the way one would approach a linear interaction effect are severe and can often result in incorrect conclusions. I cover both nonlinear effects in the context of linear regression, and—most thoroughly—nonlinear effects in models for categorical outcomes (focusing on binary logit/probit). My goal in this article is to synthesize an evolving methodological literature and to provide straightforward advice and techniques to estimate, interpret, and present nonlinear interaction effects. 

### \*Note

The template Stata files have been updated as of 2024-11-30. These versions use new code to streamline/simplify many of the tests shown in the article and includes new notes addressing common questions I receive.
