---
title: "Mize and Manago 2022 SSR"
toc: false
---

## Mize, Trenton D and Bianca Manago. 2022. "The past, present, and future of experimental methods in the social sciences." *Social Science Research.*

- [Link to PDF](https://drive.google.com/file/d/1BfewCkuOq-D8W8cAZS22PCRnfY9kcd1I/view?usp=sharing)
- [Link to article on journal's website](https://doi.org/10.1016/j.ssresearch.2022.102799)
- [Online Appendix](https://drive.google.com/file/d/1tOLySOCYrmfMrlwY3cf1EXvj0u8vcB4d/view?usp=sharing)
- [Replication files](https://drive.google.com/drive/folders/19ZX1X9veL3gL7XGEF1GG8Sv2PY7egjNm?usp=sharing)

### Abstract

In the midst of the current causal revolution, experimental methods are increasingly embraced across the social sciences. We first document the growth in the use of the experimental method and then overview the current state of the field along with suggestions for future research. Our review covers the core features of experiments that facilitate causal inference, and we offer numerous examples of different experimental designs and the types of research questions they are well-suited to test. We then harmonize popular but differing perspectives on validity in regard to experiments focused on theoretical considerations. Next, we detail a new framework of purposive sampling for social science experiments, suggesting researchers could benefit from moving beyond only two stock choices of representativeness or convenience. We then discuss issues of analysis unique to experimental data before ending with a critical discussion of null findings, open-science practices, social desirability, and other open debates in the experimental methods literature.
