---
title: "Petts, Mize, and Kaufman 2025 CWF"
toc: false
---

## Richard J. Petts, Trenton D. Mize, and Gayle Kaufman. 2025. “Does taking parental leave make you a more likeable worker? Evidence from a survey experiment.” *Community, Work, & Family.*

- [Link to PDF](https://drive.google.com/file/d/1srMgpenEePAWXWycHI_kxNHVE5YKzeMY/view?usp=sharing)
- [Link to article on journal's website](https://doi.org/10.1080/13668803.2024.2321124)
- [Replication files](https://drive.google.com/drive/folders/1hX7BPPCOTqwgxKp3BbSUbQv1tS2NbuNn?usp=sharing)
- [Online Appendix](https://drive.google.com/file/d/1kvoxUAkw2isaWg62-tBaa6tTEKNK0xTP/view?usp=sharing)

### Abstract

Sexualities scholars have long been interested in situations in which a person’s sexual identity and behavior are mismatched—e.g., when a gay or lesbian-identified person remains “closeted” and only dates different-gender partners. We argue that this mismatch represents a useful proxy for applying identity theory’s perceptual control predictions to an important topic in the sexuality literature. Using identity theory, we predict that identity discrepancies implied by sexual identity and behavior mismatches will lead to increased perceived stress, lower levels of self-esteem, and higher levels of depression. Using three waves of the National Longitudinal Study of Adolescent to Adult Health, we show that sexual-identity behavior inconsistency—our proxy measure of identity discrepancy—is associated with more stress, lower self-esteem, and more depressive symptoms. As identity theory predicts, we find that identity discrepancies are linked to worse mental health outcomes regardless of the direction of the inconsistent behavior. Overall, our findings strongly support the utility of applying identity theory to understand sexual identity processes.
