---
title: "Petts, Kincaid, Mize, and Kaufman 2025 JMF"
toc: false
---

## Petts, Richard J., Reilly Kincaid, **Trenton D. Mize**, and Gayle Kaufman. 2025. “Gone too long or back too soon? Perceptions of paid parental leave-taking and variations by gender and family structure.” *Journal of Marriage and Family.*

- [Link to PDF](https://drive.google.com/file/d/1-_1eeHoZYzoQXsXVkamGZIuCTZphhVpt/view?usp=sharing)
- [Link to article on journal's website](https://onlinelibrary.wiley.com/doi/full/10.1111/jomf.13101)
- [Replication files](https://drive.google.com/drive/folders/11N1ndqPK0EdMg5O9IREmsr8YVbQsu1wG?usp=sharing)
- [Online Appendix](https://drive.google.com/file/d/1rtLg-7a3ut32Qsr_kZntX_2s5oOKl63H/view?usp=sharing)

### Abstract

**Objective:** This study examines perceptions of paid leave-taking itself, and variations in these perceptions by parent gender, sexual orientation, and marital status. 

**Background:** Previous research largely focuses on the consequences associated with leave-taking, particularly highlighting workplace penalties associated with leave-taking. There has also been limited attention to workers with diverse family forms. We seek to better understand the culture surrounding paid parental leave in the U.S. by focusing on evaluations of leave-taking itself and whether such evaluations may reduce or exacerbate inequalities by gender, sexual orientation, and marital status. 

**Method:** We use data on 2,964 U.S. respondents from a survey experiment in which employer-offered paid parental leave-taking, parent gender, sexual orientation, and marital status were randomly assigned. We use OLS models to assess perceptions of paid leave-taking and causal effects of parent gender, sexual orientation, and marital status on these perceptions.  

**Results:** We find that respondents view 11 weeks of paid parental leave as the right amount of leave, on average. We also find variations in perceptions of leave-taking by parent gender, sexual orientation, and marital status; mothers with husbands and single parents are viewed more favorably for taking longer leaves than fathers with wives, mothers with wives, and fathers with husbands.

**Conclusion:** There is increasing support for paid leave within the U.S., but support for parents’ leave-taking largely reflects gendered stereotypes and may reinforce broader patterns of gender inequality.
