---
title: "Petts, Mize, and Kaufman 2022 SSR"
toc: false
---

## Petts, Richard J., Trenton D. Mize, and Gayle Kaufman. 2022. “Organizational Policies, Workplace Culture, and Perceived Job Commitment of Mothers and Fathers Who Take Parental Leave.” *Social Science Research.*

- [Link to PDF](https://drive.google.com/file/d/1jx7l6Rl9AbR4_YRxJZPwqWG-F0Ti1lgJ/view?usp=sharing)
- [Link to article on journal's site](https://doi.org/10.1016/j.ssresearch.2021.102651)
- [Replication Files](https://drive.google.com/drive/folders/1qLIuURbF0U4G35gxbH3RFsGZOMdfTYbU?usp=sharing)
- Blogs about the findings: [The Gender Policy Report](https://genderpolicyreport.umn.edu/paid-leave-policy-design-matters-for-workplace-equality/), [Council on Contemporary Families](https://thesocietypages.org/ccf/2021/10/19/designing-parental-leave-policies-that-reduce-stigmas-associated-with-leave-taking/)

\- Abstract: Americans do not always fully utilize available parental leave policies due (in part) to fear of a commitment penalty – where taking leave (or taking longer periods of leave) lowers perceptions of job commitment. Using a survey experiment (*N*=1,713) to identify whether organizational leave policies affect perceived job commitment, we find that leave-taking (and taking longer periods of leave) is negatively associated with perceived commitment. However, perceived commitment is higher when workers take leave under more favorable policies, and the effect of favorable policies on perceived commitment is greater for fathers than mothers. Overall, these results can help organizations design parental leave policies that increase the likelihood that workers can take needed leave without damaging their careers.
