---
title: "Petts, Kaufman, and Mize 2023 JMF"
toc: false
---

## Petts, Richard J., Gayle Kaufman, and **Trenton D. Mize**. 2023. “Parental leave-taking and perceptions of workers as good parents.” *Journal of Marriage and Family.*

- [Link to PDF](https://drive.google.com/file/d/1NNrtticf9ZvkXnRXB1UfNwFhCXqXmTlb/view?usp=sharing)
- [Link to article on journal's website](http://doi.org/10.1111/jomf.12875)
- [Online Appendix](https://drive.google.com/file/d/1jmvQUBnenam_dF6U6gw0HC1wR42R0iyA/view?usp=sharing)
- [Replication files](https://drive.google.com/drive/folders/1C8Csw-RufV7hB5VgitbfXFIwMoCyvmX4?usp=sharing)

### Abstract

**Objective**: This study examines whether parental leave-taking affects perceptions of workers as good parents, and whether this relationship varies between mothers and fathers.

**Background**: Contemporary parenthood norms promote intensive parenting, but pressures to engage in intensive parenting are more pronounced for mothers than fathers. Paid parental leave policies have the potential to improve gender equality, but only if such policies help to change gendered parenting norms. We assess whether leave-taking further entrenches gendered parenting norms within workplaces or promotes greater perceptions of good parenting among fathers. 

**Method**: We use combined data on 3,333 respondents from two survey experiments in which parental leave-taking and parental gender were randomly assigned. This enables us to assess the causal effects of parental leave-taking on perceptions of mothers and fathers as good parents.

**Results**: Mothers and fathers in married, different-sex partnerships are more likely to be viewed as good parents when they take longer periods of leave. Also, the positive effects of leave-taking on perceptions of workers as good parents are stronger for fathers than for mothers—but only for short amounts of leave taken.

**Conclusion**: Greater access to, and use of, paid parental leave may enable more parents to be perceived as fulfilling contemporary parenting norms, and may especially increase the likelihood that fathers are viewed as good parents. As such, these policies may help to change gendered perceptions of parenting and promote greater gender equality.
