---
title: "Quadlin, Mize, Doan, and Manago 2026 ASR"
toc: false
---

## Quadlin, Natasha, Trenton D. Mize, Long Doan, and Bianca Manago. Forthcoming. “What do ‘most people’ believe and who do these beliefs represent? Race-gender prototypes and the generalized other.” *American Sociological Review. *

- [Link to PDF](https://drive.google.com/file/d/1-_1eeHoZYzoQXsXVkamGZIuCTZphhVpt/view?usp=sharing) (coming soon)
- [Link to article on journal's website](https://onlinelibrary.wiley.com/doi/full/10.1111/jomf.13101) (coming soon)
- [Replication files](https://drive.google.com/drive/folders/11N1ndqPK0EdMg5O9IREmsr8YVbQsu1wG?usp=sharing) (coming soon)
- [Online Appendix](https://drive.google.com/file/d/1rtLg-7a3ut32Qsr_kZntX_2s5oOKl63H/view?usp=sharing) (coming soon)

### Abstract

When people form beliefs in social life, they often calibrate their own thinking against what they anticipate “most people” think. Although prior research demonstrates the importance of these inferences, scholars have yet to examine who is best proxied by “most people.” Given persistent inequalities in American society that advantage White men, as well as broader theories of cultural hegemony, we hypothesize that “most people’s” imagined beliefs are closely proxied by those of White men. We test these ideas using an original survey experiment (N = 2,089) in which we adapt 64 core items from the General Social Survey. Respondents were randomly assigned to answer these questions either from the perspective of most people, or from the perspective of designated race-gender groups. Contrary to our hypothesis, we find strong and consistent evidence that White men are not seen as standard-bearers for most social issues. Instead, Americans’ perceptions of what most people believe are highly aligned with the imagined beliefs of White women. Importantly, however, this pattern emerges not because White women are seen as influential, but rather because White women are perceived as less extreme than other groups. We also observe variation across respondents, such that Americans tend to center their own race-gender group in conceptualizing most people’s beliefs (with White women typically close behind).
