---
title: "irt_coef help file"
subtitle: "The installed help file, rendered for the web"
toc-depth: 3
---

::: {.callout-note appearance="simple"}
This page is generated from `irt_coef.sthlp` by `build.do`, so it matches the
installed version. In Stata, type `help irt_coef`.
:::

## Title

**`irt_coef` --** Calculates y* standardized coefficients (discrimination parameters) for binary and ordinal IRT models

## General syntax

`irt_coef` [*varlist*] `,` [options]

<span id="overview"></span>

## Overview

`irt_coef` calculates y* standardized coefficients (discrimination parameters) for binary and ordinal IRT models. The raw coefficient, standard error, and p-value are also reported alongside the y* standardized coefficient.

<span id="required"></span>

### Required Option for gsem models

<span id="required"></span>

| Option | Description |
|:--|:--|
| `latent(name)` | is required if `gsem` was used to fit the model of interest. This is the name of the latent variable that is the indepenent variable (the items are the dependent variables [i.e. the y's]). The `latent( )` option should not be used if the model was fit with the `irt` command as `irt` automatically names the latent variable *Theta*. |

### Options

| Option | Description |
|:--|:--|
| `model(name)` | specifies the name of saved model estimates to use. See `estimates store` for saving model estimates. By default, `irt_coef` will use the IRT/GSEM estimates in memory. If the relevant model estimates are not in memory, you must specify their name. |
| `decimals(#)` | changes the number of decimal places reported for the statistics. The default is 3. Any integer between 1 - 8 is allowed. |
| `sort` | orders the rows of the table based on the values of the y* standardized coefficients. |
| `title(string)` | changes the title of the table of results. A default title is automatically included. |
| `help` | prints footnotes below the table describing what the columns in the table represent. |

## Examples

```stata
webuse charity
irt grm ta1 ta2 ta3 ta4 ta5
irt_coef, help
gsem (Theta -> ta1 ta2 ta3 ta4 ta5, ologit), var(Theta@1)
irt_coef, latent(Theta)
```

## Comments

- For details on y* standardized coefficients generally see Long 1997 (pages 69-71; 128-130). In the context of IRT models, see Bartholomew et al. 2008 (pages 224-225; 259-260).

## Authorship

`irt_coef` is written by Trenton D Mize (Departments of Sociology & Statistics [by courtesy] & The Methodology Center at Purdue University). Questions can be sent to tmize@purdue.edu

## Citation

Please cite the use of irt_coef as:

Mize, Trenton D. 2024. "irt_coef: Stata command for y*-standardized coefficients in item response theory models." https://www.trentonmize.com/software/irt_coef

## References

Bartholomew, David J., Fiona Steele, Irini Moustaki, and Jane I. Galbrath. 2008. *Analysis of Multivariate Social Science Data*. Second Edition. CRC Press.

Long, J. Scott. 1997. *Regression Models for Categorical and Limited Dependent Variables*. Sage.
