---
title: "Social Psychology (Graduate)"
---

*NOTE:* Usually taught every other year.

### SOC 609 Spring 2023

MW 3:00 – 4:15pm

- [**Syllabus**](https://drive.google.com/file/d/1IY58UPtRfnnZPHLgHPTo1aZVGlJtG5Dz/view?usp=share_link)
- [**Lecture Slides**](https://drive.google.com/drive/folders/12M9NHL0BI9jv53jYm5-IiJZ-7-JZ08jD?usp=share_link)

### Course Description

Social psychologists seek to answer the questions of why do individuals do what they do, think what they think, and feel what they feel? Sociological social psychologists tend to focus on how larger macro-level factors of society such as groups, institutions, culture, and other social structures influence individual behavior, thoughts, beliefs, and emotions. Thus, social psychology provides answers as to how larger and often seemingly invisible factors influence people.

Social psychology is an interdisciplinary field with researchers across sociology, psychology, and organizational behavior actively contributing to the field. While this course will primarily focus on sociological social psychology, the distinctions between different subfields of social psychology are often blurry and we will take an inclusive approach— reading across multiple disciplines. 

This course is primarily focused on theories and theoretical perspectives. Specifically, we cover: symbolic interactionism, identity theory, social identity theory, the group position model, status characteristics theory, exchange theory, the stereotype content model, labeling/modified labeling theory, sociology of emotions, and affect control theory. We cover the specific topics of the self, social roles, identities, small groups, cooperation, status, influence, leadership, power, social cognition, stereotyping, stigma, affect, and emotions.

### Prior Course Materials

Last taught in Spring 2021:

- [**Syllabus**](https://drive.google.com/file/d/1-tDd37kdqf2fDM-X3k-CfkHEoRvcCx-s/view?usp=sharing)
- [**Lecture Slides**](https://drive.google.com/drive/folders/12M9NHL0BI9jv53jYm5-IiJZ-7-JZ08jD?usp=sharing)
- [**Assignments**](https://drive.google.com/drive/folders/1UOJUfT8qrBhMYmPRIE-JEkI_55kSmADO?usp=sharing)
