---
title: "usetdm help file"
subtitle: "The installed help file, rendered for the web"
toc-depth: 3
---

::: {.callout-note appearance="simple"}
This page is generated from `usetdm.sthlp` by `build.do`, so it matches the
installed version. In Stata, type `help usetdm`.
:::

## Title

**`usetdm` --** Command to load datasets from the web for classes and workshop

## General syntax

`usetdm` [dataname] `,` [`clear`]

<span id="overview"></span>

## Overview

`usetdm` loads datasets from the web to recreate the examples from various classes and workshops.

Option `clear` must be specified if another dataset is currently in memory.

Datasets available include: addhealth4, gss, hrs06, pew16, tenure, usstates, uscounty, world, and many more. To see the full list, [click here](https://tdmize.github.io/data/data.html).

## Examples

```stata
usetdm gss, clear
usetdm addhealth4, clear
```

## Additional Materials

Class and workshop materials are available [on the author's website.](https://www.trentonmize.com/teaching)

## Authorship

usetdm is written by Trenton D Mize, Department of Sociology, Purdue University. Questions can be sent to tmize@purdue.edu
