---
title: "mecompare_exs"
---

The `mecompare_exs` package provides example data and Stata do-files to replicate all of the examples in [Mize, Doan, and Long's 2019 article](/research/mize_doan_long_2019_SM.qmd) "A General Framework for Comparing Predictions and Marginal Effects Across Models." These are template files and are heavily annotated. 

For a Stata package that automates these tests, see [`mecompare`](/software/mecompare/index.qmd).

### Download mecompare_exs online

You can download the example files here:

- [Folder with example data and do-file](https://drive.google.com/drive/folders/1FOE-ZoluS3l1BnsMYmyxi8oWWw4dQk5N?usp=sharing)

### Download mecompare_exs in Stata

You can alternatively download the example files directly within in Stata.

To download the `mecompare_exs` example do-files and datasets, execute *both* of the following commands in Stata\*:

```stata
net install mecompare_exs, from("https://tdmize.github.io/data/mecompare_exs")
net get mecompare_exs, from("https://tdmize.github.io/data/mecompare_exs")
```

\*NOTE: The example datasets and do-files are downloaded into your working directory. To see where this is, type `pwd` in Stata.

### Citation

Please cite the use of these template files by citing the corresponding article:

Mize, Trenton D., Long Doan, and J. Scott Long. 2019. "A General Framework for Comparing Predictions and Marginal Effects Across Models." *Sociological Methodology*  49(1): 152-189.
